notifications:
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: "ZDj0AbX1hFlXrYSj0Ipjq8stQ32DB5iRmNTap+jLD63aoliWzQ+8Vmy+gls+PlfwrBBBVhZyP+LJwwVnSiEPA6gii7y2pGT4q9cGBtKi+BjHWWjsw1BfJiE0YfOnFERwaxXntrOu9n4hPWPEO9y0QQrN0UlxbOK1K1NkHZDkKJ8My0UZ9YJWlHCXJRlTbIYn7UyfQyrPMxv7h0/QtAVqmL67UO4ntbo/+QhufLao+RQjGZBEsC1hxIAA8GNG4xsfaNc26exNPj3PyD+nsrE8M8+Oo3GSZpeweX+TAwed+9qxEveWFldWnp4bkVkz7Oe/zhODXRBbuka7tO+Bq5pjvenCwSmmUtyBxNPH0fFxETRrhuzwMlDllf7U9u8fHi3shXpJjrnYKZ4J4oZUkFkgljfq71C2AY4sAe/5V9Ui4z2Qlxof+G34qQC4mCzrU2IzIoKAdBHLnksvcZk/FCIaSP3S9VY3uZBFchlGOcDtLA/GwQddXlxIPmPZwxqJGpH7m0atzbFgyB1a2BcxUBB13JRsypvBX/oQYtZ77IGN2ooqYhzh9uT871Mtyh7nj8BmbN0rDe3OacZ3IP10JbOEioYW/rpSfr6DnLOH1cw4bu9uDJ/A7/FGx9n9f951DdlpbxnuqrnEjypmjH55nOrm70DD4cDbcygLPTRwaU5+tP0="
