notifications:
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: hQhzU8nAu5GcWKHQOhVVOKNA5do1avKF/YvLKfkmNeFMQHJXOfl8UnUwPr8ySRgiWevpkcKoA6Rv44pdmQ6rRDe+8uZBoPn5/v5G92aVOAB4qiBhxyVKFFSCHCWj1pMdkdIa+6q0eu66V/4wbMAE9nRHe1wEb23PcGrJB8/OQmkIRCISzncm7olBxann3AvnD4JPnlH2QMe6O93AiCQJj4E1FzPkL/6v9vliaq26o5wkqgvqOpOQ2hXRy3cbUL38Q5HJa6N6zYAGbsMQB+0Wc97vr4ejowMp0NWGSQN0VWofEh8it3LGOyf9O0RK/6sOftRRf3oFm6vj1Jy9qvv0H6LIJ/Z9Lvo6D0OE5auc62S7j/IBlzsYFcRnYEZIhV1DRKx4xgjL3L470DTj0zidH4XRRIrj2d9oN5gb1CODbwTYEjyPX6QseAR8WAzq3yzsig2eIGnqm9vB/pDzlyoPtWVJhxTHP5/3hvn9SdrXHrU2VJpex55CoVDm7OjEAWaL+5sqs3RZEZAKROEbHcSCQaZJMGFUQjvGMojJ23E9CQpJ+NuFVRlG5rBDzqiAf/HDek1muzC2rd4lL98vG/KeM6RvMIopMGQxIZaD4Jtn9rCU9KUg1tea6ySuCnjcp6N+RujKzi5A8O/rdB0A4j6wPiQA+JA3OIVTw/swB/xlVx0=
